<?php

return [

    'profile' => [
        'archetype' => 'The Spirit of the Green Canvas',
        'kpis' => [
            'cultural_offering' => 10,
            'local_business_density' => 9,
            'business_typology' => 9,
            'presence_of_parks_and_green_areas' => 10,
            'green_space_per_capita' => 9,
            'walkability_score' => 9,
            'bike_lane_and_cyclist_safety' => 9,
            'public_transport_access' => 8,
            'average_noise_level' => 10,
            'proximity_to_highways' => 9,
            'proximity_to_nightlife_and_bars' => 8,
            'average_rent_price' => 9,
            'community_life' => 9,
            'air_quality_index' => 9,
            'commercial_vitality_indicator' => 8,
        ],
        'missing_info' => null,
    ],

    'matches' => [
        [
            "name" => "Wildasin",
            "coords" => ["lat" => 33.9892608, "lon" => -118.2992618],
            "data" => [
                "cultural_offering" => 1,
                "local_business_density" => 7,
                "business_typology" => 10,
                "presence_of_parks_and_green_areas" => 8,
                "green_space_per_capita" => 7,
                "walkability_score" => 7,
                "bike_lane_and_cyclist_safety" => 9,
                "public_transport_access" => 6,
                "average_noise_level" => 10,
                "proximity_to_highways" => 8,
                "proximity_to_nightlife_and_bars" => 4,
                "average_rent_price" => 7,
                "community_life" => 10,
                "air_quality_index" => 6,
                "commercial_vitality_indicator" => 1,
            ],
            "score" => 917,
        ],
        [
            "name" => "La Crescenta",
            "coords" => ["lat" => 34.230429, "lon" => -118.2350733],
            "data" => [
                "cultural_offering" => 4,
                "local_business_density" => 10,
                "business_typology" => 4,
                "presence_of_parks_and_green_areas" => 1,
                "green_space_per_capita" => 8,
                "walkability_score" => 9,
                "bike_lane_and_cyclist_safety" => 8,
                "public_transport_access" => 1,
                "average_noise_level" => 6,
                "proximity_to_highways" => 10,
                "proximity_to_nightlife_and_bars" => 3,
                "average_rent_price" => 10,
                "community_life" => 6,
                "air_quality_index" => 9,
                "commercial_vitality_indicator" => 5,
            ],
            "score" => 848,
        ],
        [
            "name" => "Ocean Park",
            "coords" => ["lat" => 34.0022327, "lon" => -118.4836879],
            "data" => [
                "cultural_offering" => 3,
                "local_business_density" => 4,
                "business_typology" => 8,
                "presence_of_parks_and_green_areas" => 10,
                "green_space_per_capita" => 2,
                "walkability_score" => 1,
                "bike_lane_and_cyclist_safety" => 6,
                "public_transport_access" => 9,
                "average_noise_level" => 6,
                "proximity_to_highways" => 10,
                "proximity_to_nightlife_and_bars" => 9,
                "average_rent_price" => 9,
                "community_life" => 3,
                "air_quality_index" => 10,
                "commercial_vitality_indicator" => 4,
            ],
            "score" => 843,
        ],
        [
            "name" => "Tujunga",
            "coords" => ["lat" => 34.252225, "lon" => -118.2884105],
            "data" => [
                "cultural_offering" => 10,
                "local_business_density" => 9,
                "business_typology" => 6,
                "presence_of_parks_and_green_areas" => 6,
                "green_space_per_capita" => 7,
                "walkability_score" => 7,
                "bike_lane_and_cyclist_safety" => 2,
                "public_transport_access" => 1,
                "average_noise_level" => 8,
                "proximity_to_highways" => 4,
                "proximity_to_nightlife_and_bars" => 1,
                "average_rent_price" => 4,
                "community_life" => 9,
                "air_quality_index" => 5,
                "commercial_vitality_indicator" => 9,
            ],
            "score" => 805,
        ],
        [
            "name" => "Palos Verdes Estates",
            "coords" => ["lat" => 33.7872386, "lon" => -118.401813],
            "data" => [
                "cultural_offering" => 5,
                "local_business_density" => 9,
                "business_typology" => 7,
                "presence_of_parks_and_green_areas" => 9,
                "green_space_per_capita" => 8,
                "walkability_score" => 8,
                "bike_lane_and_cyclist_safety" => 10,
                "public_transport_access" => 1,
                "average_noise_level" => 6,
                "proximity_to_highways" => 2,
                "proximity_to_nightlife_and_bars" => 6,
                "average_rent_price" => 3,
                "community_life" => 1,
                "air_quality_index" => 1,
                "commercial_vitality_indicator" => 7,
            ],
            "score" => 753,
        ],
        [
            "name" => "Lincoln Heights",
            "coords" => ["lat" => 34.0726552, "lon" => -118.2111954],
            "data" => [
                "cultural_offering" => 6,
                "local_business_density" => 2,
                "business_typology" => 6,
                "presence_of_parks_and_green_areas" => 10,
                "green_space_per_capita" => 8,
                "walkability_score" => 5,
                "bike_lane_and_cyclist_safety" => 2,
                "public_transport_access" => 1,
                "average_noise_level" => 10,
                "proximity_to_highways" => 5,
                "proximity_to_nightlife_and_bars" => 7,
                "average_rent_price" => 5,
                "community_life" => 1,
                "air_quality_index" => 6,
                "commercial_vitality_indicator" => 4,
            ],
            "score" => 716,
        ],
        [
            "name" => "Rancho Dominguez",
            "coords" => ["lat" => 33.8595564, "lon" => -118.2167197],
            "data" => [
                "cultural_offering" => 4,
                "local_business_density" => 1,
                "business_typology" => 10,
                "presence_of_parks_and_green_areas" => 8,
                "green_space_per_capita" => 4,
                "walkability_score" => 4,
                "bike_lane_and_cyclist_safety" => 4,
                "public_transport_access" => 5,
                "average_noise_level" => 3,
                "proximity_to_highways" => 3,
                "proximity_to_nightlife_and_bars" => 9,
                "average_rent_price" => 6,
                "community_life" => 10,
                "air_quality_index" => 4,
                "commercial_vitality_indicator" => 4,
            ],
            "score" => 708,
        ],
        [
            "name" => "Watts",
            "coords" => ["lat" => 33.9405897, "lon" => -118.2428984],
            "data" => [
                "cultural_offering" => 4,
                "local_business_density" => 3,
                "business_typology" => 1,
                "presence_of_parks_and_green_areas" => 6,
                "green_space_per_capita" => 5,
                "walkability_score" => 5,
                "bike_lane_and_cyclist_safety" => 6,
                "public_transport_access" => 6,
                "average_noise_level" => 8,
                "proximity_to_highways" => 9,
                "proximity_to_nightlife_and_bars" => 2,
                "average_rent_price" => 5,
                "community_life" => 6,
                "air_quality_index" => 3,
                "commercial_vitality_indicator" => 6,
            ],
            "score" => 679,
        ],
        [
            "name" => "Venice",
            "coords" => ["lat" => 33.995044, "lon" => -118.4668875],
            "data" => [
                "cultural_offering" => 1,
                "local_business_density" => 6,
                "business_typology" => 1,
                "presence_of_parks_and_green_areas" => 9,
                "green_space_per_capita" => 3,
                "walkability_score" => 6,
                "bike_lane_and_cyclist_safety" => 8,
                "public_transport_access" => 1,
                "average_noise_level" => 9,
                "proximity_to_highways" => 5,
                "proximity_to_nightlife_and_bars" => 2,
                "average_rent_price" => 7,
                "community_life" => 4,
                "air_quality_index" => 6,
                "commercial_vitality_indicator" => 3,
            ],
            "score" => 652,
        ],
        [
            "name" => "Van Ness",
            "coords" => ["lat" => 33.9830173, "lon" => -118.3196032],
            "data" => [
                "cultural_offering" => 3,
                "local_business_density" => 3,
                "business_typology" => 4,
                "presence_of_parks_and_green_areas" => 3,
                "green_space_per_capita" => 7,
                "walkability_score" => 4,
                "bike_lane_and_cyclist_safety" => 4,
                "public_transport_access" => 5,
                "average_noise_level" => 2,
                "proximity_to_highways" => 10,
                "proximity_to_nightlife_and_bars" => 10,
                "average_rent_price" => 2,
                "community_life" => 9,
                "air_quality_index" => 4,
                "commercial_vitality_indicator" => 1,
            ],
            "score" => 631,
        ],
    ],

    'justification' =>
    "My Lord/Lady, for 'The Spirit of the Green Canvas', I commend Wildasin as your ideal stronghold. 
        This realm boasts a profound quietude, ensuring your creative thoughts flow undisturbed, a perfect match for your need for peace. 
        Its verdant parks and ample green spaces offer a boundless canvas for your inspiration, while the diverse local businesses provide the very tools for your craft.

        Furthermore, Wildasin's strong community life shall foster a true sense of belonging, and its excellent cycling paths, coupled with strategic proximity to the King's Road, ensure ease of movement throughout the lands. Here, your noble spirit shall truly flourish.",
];
